### ISSUE TITLE
Common Data -> Repository Data Directory

### ISSUE THREAD

**Issue by unfiltered-admin** [StopTheSteal/StopTheSteal#1]
Let's try putting any common data, especially source data into the Data directory so we're not duplicating anything.  We'll need to update any references in our code to correspond with any changes.  Open to ideas for folder structure and any file naming conventions.  

My initial thoughts on "Data" folder structure:

Data\Analysis
Data\Counties\JSON
Data\Counties\CSV
Data\National
Data\Postgresql
Data\Precincts\JSON
Data\Precincts\CSV
Data\States\JSON
Data\States\CSV

**Comment by quant-manager** [comment]
This is my current structure:

Module #1 (main_election_fractions_timeseries_analyzer.R)

Input JSON
https://github.com/StopTheSteal/StopTheSteal/tree/main/Analytics/Scripts/r/input/elections-assets/2020/data/api/2020-11-03/race-page
Output CSV
https://github.com/StopTheSteal/StopTheSteal/tree/main/Analytics/Scripts/r/input/elections-assets/2020/data/api/2020-11-03/race-page


Module # 2 (main_election_counts_timeseries_analyzer.R)

Input JSON
https://github.com/StopTheSteal/StopTheSteal/tree/main/Analytics/Scripts/r/input/elections-assets/2020/data/precincts
Output CSV
https://github.com/StopTheSteal/StopTheSteal/tree/main/Analytics/Scripts/r/input/elections-assets/2020/data/precincts/csv
Output RDS
https://github.com/StopTheSteal/StopTheSteal/tree/main/Analytics/Scripts/r/input/elections-assets/2020/data/precincts/rds
Output PDF:
https://github.com/StopTheSteal/StopTheSteal/tree/main/Analytics/Scripts/r/output/pdf
Output JPEG:
TBD
Output CSV
TBD

If you change it, please provide exact mapping for all of the above directories. Then you may move the files around.

Note that even the input JSON files may be updated by my program from the Internet (these files are shared across languages!). In addition, we need to assure dedicated module-specific output directories for each file type. In other words, Python output should be separate from R output!

Note that the links that we already posted online for other have to be updated as well!

**Comment by quant-manager** [comment]
One more thing: my entire schema must be in the same directory. For example. all my existing CSV tables must be in the same directory (same hold for RDS), regardless whether they are on the precinct or county level. Output CSVs may be separated though, as you suggested. I have not generated output CSVs yet.

**Comment by td-fugg** [comment]
@unfilter  I have the postgres data in the Data folder, the sql in the scripts folder is the db schema, not user data. But if you see something I misplaced, feel free to organize it, or let me know where you want it.  @quant-manager  is there hard-coding or something that prevents the data and code from being organized differently?

**Comment by quant-manager** [comment]
@td-fugg , I have already described what I need (see above). If you really want to move my files, then go ahead, but follow my needs (see above). I am happy with my current setup for now.

**Comment by quant-manager** [comment]
@td-fugg , I asked you to "move", but not to "upload" my files. Where is the most recent version of https://github.com/StopTheSteal/StopTheSteal/blob/main/Analytics/Scripts/r/main_scraper_single_thread.R?

**Comment by dorseyroach** [comment]
Hey @quant-manager - This might have been my fault.  It looks like when I merged fugg's branch into main it may not have had the latest version of the script.  Is this the most recent version?
https://github.com/StopTheSteal/StopTheSteal/blob/fab25cbeaa09da04696d1dd17499e1c839f5d91a/Scripts.R/main_scraper_single_thread.R

With regards to the file locations, I know you can use symbolic links on Unix based systems, but in windows it's kind of sketchy.  I'm fine leaving the R script input data where it is as long as you guys don't mind the extra bloat in the repository.

**Comment by unfiltered-admin** [comment]
Hey @quant-manager - This might have been my fault. It looks like when I merged fugg's branch into main it may not have had the latest version of the script. Is this the most recent version?
https://github.com/StopTheSteal/StopTheSteal/blob/fab25cbeaa09da04696d1dd17499e1c839f5d91a/Scripts.R/main_scraper_single_thread.R

With regards to the file locations, I know you can use symbolic links on Unix based systems, but in windows it's kind of sketchy. I'm fine leaving the R script input data where it is as long as you guys don't mind the extra bloat in the repository.

**Comment by quant-manager** [comment]
Hi @unfilter ! Thanks for recovering the file. I have updated it. I will update my paths in my R code later.
Do not worry about the bloating size. If we find more JSON files, I will add them. Other than that, my output
will have very modest size. We can revisit this topic later. I just feel that sharing files (even input files) at this stage may be
inconvenient.
